name: 'Build and deploy app'
 
# The workflow should only trigger on push events to the main branch
# Deleted and recreated the IdP

on : workflow_dispatch

#on:
 #push:
  #branches:
   #- main

env: 
 STAGE: dev
 CONTAINER_PORT: 8080
 REPOSITORY: my-ecr-repo
 IMAGE_TAG: ${{ github.sha }}
 CLUSTER: FargateECSCluster

jobs:
    docker-build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
  
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push docker image to Amazon ECR
          id: build-image
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          run: |
            docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
            
        - name: Deploy to AWS CloudFormation
          uses: aws-actions/aws-cloudformation-github-deploy@v1
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            IMAGE_URI: $REGISTRY/$REPOSITORY:$IMAGE_TAG
          with:
             name: new-stack
             template: Fargate-Cluster.yml
             parameter-overrides: "Stage=$STAGE,ContainerPort=8080,ImageURI=$IMAGE_URI"
             capabilities: CAPABILITY_NAMED_IAM
