name: 'Build and ECR store'
 
# The workflow should only trigger on push events to the main branch
# Deleted and recreated the IdP

on : workflow_dispatch

#on:
 #push:
  #branches:
   #- main
 
# Required to get the ID Token that will be used for OIDC
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
    docker-build-and-push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repo
          uses: actions/checkout@v3
  
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2 # More information on this action can be found below in the 'AWS Credentials' section
          with:
            aws-region: eu-central-1
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_accesskey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            role-to-assume: arn:aws:iam::981847621073:role/github-exid-push-pull
            role-session-name: github-session

        - name: Login to Amazon ECR
          id: login-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build, tag, and push docker image to Amazon ECR
          env:
            REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            REPOSITORY: my-ecr-repo
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
            docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
