AWSTemplateFormatVersion: 2010-09-09
Description: The CloudFormation template for the task definition

Parameters:
  Stage:
    Type: String
    Default: dev
  ContainerPort:
    Type: Number
    Default: 80
  ImageURI:
    Type: StringTaskDefinition:
    
 Resources:
 
 Type: AWS::ECS::TaskDefinition
    Properties: 
      Memory: 1024
      Cpu: 512
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - 'FARGATE'
      TaskRoleArn: !Ref ExecutionRole
      ExecutionRoleArn: !Ref ExecutionRole
      ContainerDefinitions:
        - Name: !Join ['-', [!Ref Stage, !Ref 'AWS::AccountId', 'Container']]
          Image: !Ref ImageURI
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              HostPort: !Ref ContainerPort
